spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
        show-sql: true
        database: postgresql
    security:
        user:
            name: ${SECURITY_USERNAME:user}
            password: ${SECURITY_PASSWORD:123}
logging:
    level:
        org:
            springframework:
                security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
    pattern:
        console: '${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}'